Linter added for go and javascript
hyperledger/caliper-benchmarks pull request #259
Opened 2024-04-10 21:25 UTC by kartikaysaxena

Fixes #215

2024-04-12 16:43 UTC, kartikaysaxena commented
PTAL @davidkel

2024-04-16 08:09 UTC, davidkel commented
@kartikaysaxena I really like the idea you have put forward but I think the actual work is more comprehensive than this PR. I have captured my thoughts in this issue #262 
Please add to the issue any thoughts you have and if you are interested I can assign the issue to you.

2024-04-16 08:09 UTC, davidkel requested changes
see comment in PR

2025-04-25 22:01 UTC, davidkel commented
closing as no response.

2025-04-25 22:01 UTC, closed without merging